MAIN = converter
CC = g++

INCLUDE_PATH = 
LIB_PATH = 
LIB =
FLAGS = -O3
EXTENSIONS =*.cpp

COMPILE_STRING = $(CC) -o $(MAIN) $(INCLUDE_PATH) $(LIB_PATH) $(LIB) $(FLAGS) $(EXTENSIONS)

prog : $(MAIN)
$(MAIN) : 
	$(COMPILE_STRING)

all: $(MAIN)

clean: 
	-rm converter

	
	
