# Try to find PAPI headers and libraries.
#
# Usage of this module as follows:
#
#     find_package(OpenCL)

FIND_LIBRARY(OPENCL_LIBRARIES OpenCL
  ENV LD_LIBRARY_PATH
)
GET_FILENAME_COMPONENT(OPENCL_LIB_DIR ${OPENCL_LIBRARIES} PATH)
GET_FILENAME_COMPONENT(_OPENCL_INC_CAND ${OPENCL_LIB_DIR}/../../include ABSOLUTE)

 
FIND_PATH(OPENCL_INCLUDE_DIRS CL/cl.h PATHS ${_OPENCL_INC_CAND} "/opt/cuda/include")
FIND_PATH(_OPENCL_CPP_INCLUDE_DIRS CL/cl.hpp PATHS ${_OPENCL_INC_CAND} "/opt/cuda/include")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OpenCL DEFAULT_MSG 
      OPENCL_INCLUDE_DIRS
      _OPENCL_CPP_INCLUDE_DIRS
      OPENCL_LIBRARIES
)

MARK_AS_ADVANCED( OPENCL_INCLUDE_DIRS _OPENCL_CPP_INCLUDE_DIRS  )
